version: 2.1
description: |
  testing Circleci- test, docker_build and setup_terraform_infra

# orbs:
#   terraform: 'circleci/terraform@1.1.0'

workflows:
  main:
    jobs:
      - test
      - docker_build:
          requires:
            - test

jobs:
  test:
    docker:
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - run:
          name: Install python dependency in a venv
          command: |
            python -m venv venv
            . venv/bin/activate
            pip -q install -r requirements.txt
            pip install pytest
      - run:
          name: Run python example test cases
          command: |
            . venv/bin/activate
            python -m pytest .\test\
      - run: echo "testing ends"
  docker_build:
    # filters:
    #   branches:
    #     only:
    #       - master
    docker:
      # https://circleci.com/docs/2.0/circleci-images/#python
      - image: circleci/python:3.8-buster
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build docker image
          command: >
            docker build -t rishi/test-flask .
  
  # setup_terraform_infra:
  #   steps:
  #     - checkout
  #     - run:
  #         name: Terraform initialize
  #         command: >
  #           terraform init
  #     - run:
  #         name: Deploy Develop to AWS
